export const FETCH_PAINTINGS = 'FETCH_PAINTINGS';
export const SELECT_ACTIVE_PAINTING = 'SELECT_ACTIVE_PAINTING';
export const DELETE_PAINTING = 'DELETE_PAINTING';
export const All_MUSEUMS = 'All_MUSEUMS';
export const DC_MUSEUMS = 'DC_MUSEUMS';
